Repository k8s-at-home/charts, pull requests merged in 2021-11, with the labels that each got.

#1263 [vaultwarden] Update persistence example
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/README.md
  charts/stable/vaultwarden/README_CHANGELOG.md.gotmpl
  charts/stable/vaultwarden/README_CONFIG.md.gotmpl
  charts/stable/vaultwarden/ci/ct-values.yaml
  charts/stable/vaultwarden/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1255 [lancache] Add new chart.
  charts/incubator/lancache/.helmignore
  charts/incubator/lancache/Chart.yaml
  charts/incubator/lancache/README.md
  charts/incubator/lancache/README.md.gotmpl
  charts/incubator/lancache/README_CHANGELOG.md.gotmpl
  charts/incubator/lancache/README_CONFIG.md.gotmpl
  charts/incubator/lancache/templates/NOTES.txt
  charts/incubator/lancache/templates/common.yaml
  charts/incubator/lancache/values.yaml
Labels: new chart, precommit:ok, install:ok, lint:ok

#1266 [xbvr] Add new chart
  charts/stable/xbvr/.helmignore
  charts/stable/xbvr/Chart.yaml
  charts/stable/xbvr/README.md
  charts/stable/xbvr/README.md.gotmpl
  charts/stable/xbvr/README_CHANGELOG.md.gotmpl
  charts/stable/xbvr/README_CONFIG.md.gotmpl
  charts/stable/xbvr/templates/NOTES.txt
  charts/stable/xbvr/templates/common.yaml
  charts/stable/xbvr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1273 [deepstack] feat(deepstack): initial addition of deepstack chart
  charts/stable/deepstack/.helmignore
  charts/stable/deepstack/Chart.yaml
  charts/stable/deepstack/README.md
  charts/stable/deepstack/README.md.gotmpl
  charts/stable/deepstack/README_CHANGELOG.md.gotmpl
  charts/stable/deepstack/README_CONFIG.md.gotmpl
  charts/stable/deepstack/templates/NOTES.txt
  charts/stable/deepstack/templates/common.yaml
  charts/stable/deepstack/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1271 [double-take] feat(double-take): initial commit
  charts/stable/double-take/.helmignore
  charts/stable/double-take/Chart.yaml
  charts/stable/double-take/README.md
  charts/stable/double-take/README.md.gotmpl
  charts/stable/double-take/README_CHANGELOG.md.gotmpl
  charts/stable/double-take/README_CONFIG.md.gotmpl
  charts/stable/double-take/templates/NOTES.txt
  charts/stable/double-take/templates/common.yaml
  charts/stable/double-take/templates/configmap.yaml
  charts/stable/double-take/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1275 [deepstack] add deepstack-ui
  charts/stable/deepstack/Chart.yaml
  charts/stable/deepstack/README.md
  charts/stable/deepstack/README_CHANGELOG.md.gotmpl
  charts/stable/deepstack/templates/common.yaml
  charts/stable/deepstack/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1253 [filebrowser] add new filebrowser chart
  CODE_OF_CONDUCT.md
  charts/README.md
  charts/stable/filebrowser/.helmignore
  charts/stable/filebrowser/Chart.yaml
  charts/stable/filebrowser/README.md
  charts/stable/filebrowser/README.md.gotmpl
  charts/stable/filebrowser/README_CHANGELOG.md.gotmpl
  charts/stable/filebrowser/README_CONFIG.md.gotmpl
  charts/stable/filebrowser/templates/NOTES.txt
  charts/stable/filebrowser/templates/common.yaml
  charts/stable/filebrowser/templates/configmap.yaml
  charts/stable/filebrowser/values.yaml
Labels: new chart, precommit:ok, install:ok, lint:ok

#1267 [photoprism] Update photoprism image
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/README.md
  charts/stable/photoprism/README_CHANGELOG.md.gotmpl
  charts/stable/photoprism/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1284 [beets] Add beets chart
  charts/stable/beets/.helmignore
  charts/stable/beets/Chart.yaml
  charts/stable/beets/README.md
  charts/stable/beets/README.md.gotmpl
  charts/stable/beets/README_CHANGELOG.md.gotmpl
  charts/stable/beets/README_CONFIG.md.gotmpl
  charts/stable/beets/templates/NOTES.txt
  charts/stable/beets/templates/common.yaml
  charts/stable/beets/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1268 [vikunja] Improve Vikunja chart.
  charts/stable/vikunja/Chart.yaml
  charts/stable/vikunja/README.md
  charts/stable/vikunja/README_CHANGELOG.md.gotmpl
  charts/stable/vikunja/templates/common.yaml
  charts/stable/vikunja/templates/configmap.yaml
  charts/stable/vikunja/values.yaml
Labels: precommit:ok, install:ok, lint:ok
