Repository k8s-at-home/charts, pull requests merged in 2021-10, with the labels that each got.

#1223 [anonaddy] Create Helm Chart
  charts/stable/anonaddy/.helmignore
  charts/stable/anonaddy/Chart.yaml
  charts/stable/anonaddy/README.md
  charts/stable/anonaddy/README.md.gotmpl
  charts/stable/anonaddy/README_CHANGELOG.md.gotmpl
  charts/stable/anonaddy/README_CONFIG.md.gotmpl
  charts/stable/anonaddy/ci/ct-values.yaml
  charts/stable/anonaddy/templates/NOTES.txt
  charts/stable/anonaddy/templates/common.yaml
  charts/stable/anonaddy/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1225 [vaultwarden] Bumped vaultwarden/server to 1.22.2
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/README.md
  charts/stable/vaultwarden/README_CHANGELOG.md.gotmpl
  charts/stable/vaultwarden/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1226 [focalboard] Change focalboard image to Official
  charts/stable/focalboard/Chart.yaml
  charts/stable/focalboard/README.md
  charts/stable/focalboard/README_CHANGELOG.md.gotmpl
  charts/stable/focalboard/templates/common.yaml
  charts/stable/focalboard/templates/configmap.yaml
  charts/stable/focalboard/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1227 [sonarr] Uplifted Sonarr version to v3.0.6.1342
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/README_CHANGELOG.md.gotmpl
  charts/stable/sonarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1228 [jellyfin] Uplifted Jellyfin image version to 10.7.7
  charts/stable/jellyfin/Chart.yaml
  charts/stable/jellyfin/README.md
  charts/stable/jellyfin/README_CHANGELOG.md.gotmpl
  charts/stable/jellyfin/values.yaml
Labels: precommit:ok, lint:ok

#1229 [syncthing] Uplifted syncthing image version to 1.18.2
  charts/stable/syncthing/Chart.yaml
  charts/stable/syncthing/README.md
  charts/stable/syncthing/README_CHANGELOG.md.gotmpl
  charts/stable/syncthing/values.yaml
Labels: precommit:ok, install:ok, lint:ok, hacktoberfest-accepted

#1230 [bazarr] Uplifted Bazarr image version to 0.9.9
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/README.md
  charts/stable/bazarr/README_CHANGELOG.md.gotmpl
  charts/stable/bazarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, hacktoberfest-accepted

#1232 [openhab] Add new chart.
  charts/incubator/openhab/Chart.yaml
  charts/incubator/openhab/README.md
  charts/incubator/openhab/README.md.gotmpl
  charts/incubator/openhab/README_CHANGELOG.md.gotmpl
  charts/incubator/openhab/README_CONFIG.md.gotmpl
  charts/incubator/openhab/templates/NOTES.txt
  charts/incubator/openhab/templates/common.yaml
  charts/incubator/openhab/templates/configmap.yaml
  charts/incubator/openhab/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1257 [home-assistant] Fix home-assistant ingress example
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/README_CHANGELOG.md.gotmpl
  charts/stable/home-assistant/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok
