Repository k8s-at-home/charts, pull requests merged in 2021-12, with the labels that each got.

#1291 [tautuli] Image version bump
  charts/stable/tautulli/Chart.yaml
  charts/stable/tautulli/README.md
  charts/stable/tautulli/README_CHANGELOG.md.gotmpl
  charts/stable/tautulli/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1290 [changedetection-io] Image version bump and fixes
  charts/incubator/changedetection-io/Chart.yaml
  charts/incubator/changedetection-io/README.md
  charts/incubator/changedetection-io/README_CHANGELOG.md.gotmpl
  charts/incubator/changedetection-io/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1292 [mealie] - Support Postgres
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/README.md
  charts/stable/mealie/README_CHANGELOG.md.gotmpl
  charts/stable/mealie/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1294 [tdarr] Add shared persistence to tdarr node sidecar
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/README_CHANGELOG.md.gotmpl
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1295 [tdarr] Allow definition of resources for the node
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/README_CHANGELOG.md.gotmpl
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1296 [changedetection-io] image version bump
  charts/incubator/changedetection-io/Chart.yaml
  charts/incubator/changedetection-io/README.md
  charts/incubator/changedetection-io/README_CHANGELOG.md.gotmpl
  charts/incubator/changedetection-io/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1298 [onedrive] Bump image tag to 2.0.5
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/README.md
  charts/stable/onedrive/README_CHANGELOG.md.gotmpl
  charts/stable/onedrive/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1288 [uptime-kuma] Add new chart
  charts/stable/uptime-kuma/.helmignore
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/README.md
  charts/stable/uptime-kuma/README.md.gotmpl
  charts/stable/uptime-kuma/README_CHANGELOG.md.gotmpl
  charts/stable/uptime-kuma/README_CONFIG.md.gotmpl
  charts/stable/uptime-kuma/templates/NOTES.txt
  charts/stable/uptime-kuma/templates/common.yaml
  charts/stable/uptime-kuma/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1302 [uptime-kuma] Update persistence to map data volume to /app/data
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/README.md
  charts/stable/uptime-kuma/README_CHANGELOG.md.gotmpl
  charts/stable/uptime-kuma/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1305 [unifi] Update AppVersion to v6.5.54
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/README.md
  charts/stable/unifi/README_CHANGELOG.md.gotmpl
  charts/stable/unifi/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1304 [tdarr] Fix Tdarr node resource indentation
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/README_CHANGELOG.md.gotmpl
  charts/stable/tdarr/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok

#1308 [tdarr] Add ffmpegPath environment override
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/README_CHANGELOG.md.gotmpl
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1309 [ghost] Add new chart
  charts/stable/ghost/Chart.yaml
  charts/stable/ghost/README.md
  charts/stable/ghost/README.md.gotmpl
  charts/stable/ghost/README_CHANGELOG.md.gotmpl
  charts/stable/ghost/README_CONFIG.md.gotmpl
  charts/stable/ghost/ci/ct-values.yaml
  charts/stable/ghost/templates/NOTES.txt
  charts/stable/ghost/templates/common.yaml
  charts/stable/ghost/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1313 [lidarr/sonarr/radarr] Updating the exportarr image patch level
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/values.yaml
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/values.yaml
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/values.yaml
Labels: kind:incomplete-docs, kind:incorrect-title, precommit:ok, install:ok, lint:ok

#1324 [focalboard] Add serviceLinks docs
  charts/stable/focalboard/Chart.yaml
  charts/stable/focalboard/README.md
  charts/stable/focalboard/README_CHANGELOG.md.gotmpl
  charts/stable/focalboard/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok

#1323 [vaultwarden] Use port names in ingress setup
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/README.md
  charts/stable/vaultwarden/README_CHANGELOG.md.gotmpl
  charts/stable/vaultwarden/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1322 [searx] feat: enable optional resources for all containers
  charts/stable/searx/Chart.yaml
  charts/stable/searx/README.md
  charts/stable/searx/README_CHANGELOG.md.gotmpl
  charts/stable/searx/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok

#1327 [reverse-proxy] Fix ingressclass generation
  charts/stable/reverse-proxy/Chart.yaml
  charts/stable/reverse-proxy/README.md
  charts/stable/reverse-proxy/README_CHANGELOG.md.gotmpl
  charts/stable/reverse-proxy/templates/ingress.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1328 [mealie] Fix postgresql subchart name
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/README.md
  charts/stable/mealie/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1330 [cryptpad] Add chart (wip, rfc)
  charts/incubator/cryptpad/.helmignore
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/README.md
  charts/incubator/cryptpad/README.md.gotmpl
  charts/incubator/cryptpad/README_CHANGELOG.md.gotmpl
  charts/incubator/cryptpad/README_CONFIG.md.gotmpl
  charts/incubator/cryptpad/templates/NOTES.txt
  charts/incubator/cryptpad/templates/common.yaml
  charts/incubator/cryptpad/templates/configmap.yaml
  charts/incubator/cryptpad/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1331 [openhab] update to openhab 3.2.0
  charts/incubator/openhab/Chart.yaml
  charts/incubator/openhab/README.md
  charts/incubator/openhab/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1329 [alertmanager-discord] Add new chart
  .github/ct-install.yaml
  charts/stable/alertmanager-discord/.helmignore
  charts/stable/alertmanager-discord/Chart.yaml
  charts/stable/alertmanager-discord/README.md
  charts/stable/alertmanager-discord/README.md.gotmpl
  charts/stable/alertmanager-discord/README_CHANGELOG.md.gotmpl
  charts/stable/alertmanager-discord/README_CONFIG.md.gotmpl
  charts/stable/alertmanager-discord/templates/NOTES.txt
  charts/stable/alertmanager-discord/templates/common.yaml
  charts/stable/alertmanager-discord/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1332 [blocky] update to blocky v0.17
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/README_CHANGELOG.md.gotmpl
  charts/stable/blocky/templates/servicemonitor.yaml
  charts/stable/blocky/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1306 [frigate] update frigate version to 0.9.4
  charts/stable/frigate/Chart.yaml
  charts/stable/frigate/README.md
  charts/stable/frigate/README_CHANGELOG.md.gotmpl
  charts/stable/frigate/ci/ct-values.yaml
  charts/stable/frigate/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1321 [double-take] Make detectors and notifiers optional
  charts/stable/double-take/Chart.yaml
  charts/stable/double-take/README.md
  charts/stable/double-take/README_CHANGELOG.md.gotmpl
  charts/stable/double-take/templates/configmap.yaml
  charts/stable/double-take/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1340 [cryptpad] add default podSecurityContext
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1337 [blocky] use container image direct from the application developer
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/README_CHANGELOG.md.gotmpl
  charts/stable/blocky/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok
