Repository k8s-at-home/charts, pull requests merged in 2021-07, with the labels that each got.

#1079 [apache-musicindex] Use standard ports
  charts/stable/apache-musicindex/Chart.yaml
  charts/stable/apache-musicindex/README.md
  charts/stable/apache-musicindex/README_CHANGELOG.md.gotmpl
  charts/stable/apache-musicindex/README_CONFIG.md.gotmpl
  charts/stable/apache-musicindex/values.yaml
Labels: bug

#1083 initial add for openkm
  charts/stable/openkm/.helmignore
  charts/stable/openkm/Chart.yaml
  charts/stable/openkm/README.md
  charts/stable/openkm/README.md.gotmpl
  charts/stable/openkm/README_CHANGELOG.md.gotmpl
  charts/stable/openkm/README_CONFIG.md.gotmpl
  charts/stable/openkm/templates/NOTES.txt
  charts/stable/openkm/templates/common.yaml
  charts/stable/openkm/values.yaml
Labels: new chart

#1089 [amcrest2mqtt] Add chart
  .github/ct-install.yaml
  charts/stable/amcrest2mqtt/.helmignore
  charts/stable/amcrest2mqtt/Chart.yaml
  charts/stable/amcrest2mqtt/README.md
  charts/stable/amcrest2mqtt/README.md.gotmpl
  charts/stable/amcrest2mqtt/README_CHANGELOG.md.gotmpl
  charts/stable/amcrest2mqtt/README_CONFIG.md.gotmpl
  charts/stable/amcrest2mqtt/templates/NOTES.txt
  charts/stable/amcrest2mqtt/templates/common.yaml
  charts/stable/amcrest2mqtt/values.yaml
  templates/chart/Chart.yaml
Labels: enhancement, install:ok, lint:ok, new chart, precommit:ok

#1091 [frigate] chart based on common
  charts/stable/frigate/.helmignore
  charts/stable/frigate/Chart.yaml
  charts/stable/frigate/README.md
  charts/stable/frigate/README.md.gotmpl
  charts/stable/frigate/README_CHANGELOG.md.gotmpl
  charts/stable/frigate/README_CONFIG.md.gotmpl
  charts/stable/frigate/templates/NOTES.txt
  charts/stable/frigate/templates/common.yaml
  charts/stable/frigate/templates/configmap.yaml
  charts/stable/frigate/values.yaml
Labels: install:ok, lint:ok, precommit:ok

#1102 [blocky] Move replicas under controller definition in values.yaml
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/values.yaml
Labels: install:ok, lint:ok, precommit:ok

#1099 [gollum] Fixes for init and cron
  charts/stable/gollum/Chart.yaml
  charts/stable/gollum/README.md
  charts/stable/gollum/README_CHANGELOG.md.gotmpl
  charts/stable/gollum/templates/common.yaml
  charts/stable/gollum/templates/configmap.yaml
Labels: install:ok, lint:ok, precommit:ok
