Repository k8s-at-home/charts, pull requests merged in 2021-05, with the labels that each got.

#898 [meta] Added task badge [ci-skip]
  README.md
Labels: documentation

#896 [truecommand] New Chart
  charts/stable/truecommand/.helmignore
  charts/stable/truecommand/Chart.yaml
  charts/stable/truecommand/README.md
  charts/stable/truecommand/README.md.gotmpl
  charts/stable/truecommand/README_CHANGELOG.md.gotmpl
  charts/stable/truecommand/README_CONFIG.md.gotmpl
  charts/stable/truecommand/templates/NOTES.txt
  charts/stable/truecommand/templates/common.yaml
  charts/stable/truecommand/values.yaml
Labels: new chart

#897 [pyload] Updated icon url
  charts/stable/pyload/Chart.yaml
  charts/stable/pyload/README.md
  charts/stable/pyload/README.md.gotmpl
  charts/stable/pyload/README_CHANGELOG.md.gotmpl
Labels: enhancement

#895 [openemr] New chart
  charts/stable/openemr/.helmignore
  charts/stable/openemr/Chart.yaml
  charts/stable/openemr/README.md
  charts/stable/openemr/README.md.gotmpl
  charts/stable/openemr/README_CHANGELOG.md.gotmpl
  charts/stable/openemr/README_CONFIG.md.gotmpl
  charts/stable/openemr/ci/ct-values.yaml
  charts/stable/openemr/templates/NOTES.txt
  charts/stable/openemr/templates/common.yaml
  charts/stable/openemr/values.yaml
Labels: new chart

#900 [teslamate] Migrate to common library
  charts/stable/teslamate/Chart.yaml
  charts/stable/teslamate/README.md
  charts/stable/teslamate/README.md.gotmpl
  charts/stable/teslamate/README_CHANGELOG.md.gotmpl
  charts/stable/teslamate/ci/ct-values.yaml
  charts/stable/teslamate/templates/NOTES.txt
  charts/stable/teslamate/templates/_helpers.tpl
  charts/stable/teslamate/templates/common.yaml
  charts/stable/teslamate/templates/deployment.yaml
  charts/stable/teslamate/templates/ingress.yaml
  charts/stable/teslamate/templates/service.yaml
  charts/stable/teslamate/templates/tests/test-connection.yaml
  charts/stable/teslamate/values.yaml
Labels: enhancement

#903 [intel-gpu-plugin] Migrate to common library
  charts/stable/intel-gpu-plugin/Chart.yaml
  charts/stable/intel-gpu-plugin/README.md
  charts/stable/intel-gpu-plugin/README.md.gotmpl
  charts/stable/intel-gpu-plugin/README_CHANGELOG.md.gotmpl
  charts/stable/intel-gpu-plugin/templates/NOTES.txt
  charts/stable/intel-gpu-plugin/templates/_helpers.tpl
  charts/stable/intel-gpu-plugin/templates/common.yaml
  charts/stable/intel-gpu-plugin/templates/daemonset.yaml
  charts/stable/intel-gpu-plugin/templates/serviceaccount.yaml
  charts/stable/intel-gpu-plugin/values.yaml
Labels: enhancement

#908 [shlink] New chart
  charts/stable/shlink/.helmignore
  charts/stable/shlink/Chart.yaml
  charts/stable/shlink/README.md
  charts/stable/shlink/README.md.gotmpl
  charts/stable/shlink/README_CHANGELOG.md.gotmpl
  charts/stable/shlink/README_CONFIG.md.gotmpl
  charts/stable/shlink/templates/NOTES.txt
  charts/stable/shlink/templates/common.yaml
  charts/stable/shlink/values.yaml
Labels: new chart

#902 [uptimerobot-prometheus] Migrated to common library
  charts/stable/uptimerobot-prometheus/Chart.yaml
  charts/stable/uptimerobot-prometheus/README.md
  charts/stable/uptimerobot-prometheus/README.md.gotmpl
  charts/stable/uptimerobot-prometheus/README_CHANGELOG.md.gotmpl
  charts/stable/uptimerobot-prometheus/templates/NOTES.txt
  charts/stable/uptimerobot-prometheus/templates/_helpers.tpl
  charts/stable/uptimerobot-prometheus/templates/common.yaml
  charts/stable/uptimerobot-prometheus/templates/deployment.yaml
  charts/stable/uptimerobot-prometheus/templates/service.yaml
  charts/stable/uptimerobot-prometheus/templates/servicemonitor.yaml
  charts/stable/uptimerobot-prometheus/values.yaml
Labels: enhancement

#889 [gollum] New Chart
  charts/stable/gollum/Chart.yaml
  charts/stable/gollum/README.md
  charts/stable/gollum/README.md.gotmpl
  charts/stable/gollum/README_CHANGELOG.md.gotmpl
  charts/stable/gollum/README_CONFIG.md.gotmpl
  charts/stable/gollum/templates/NOTES.txt
  charts/stable/gollum/templates/_additionalVolumeMounts.tpl
  charts/stable/gollum/templates/_additionalVolumes.tpl
  charts/stable/gollum/templates/_containers.tpl
  charts/stable/gollum/templates/_initContainers.yaml
  charts/stable/gollum/templates/common.yaml
  charts/stable/gollum/templates/configmap.yaml
  charts/stable/gollum/values.yaml
Labels: new chart

#920 [home-assistant] Version bump to 2021.5.5
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/README.md.gotmpl
  charts/stable/home-assistant/README_CHANGELOG.md.gotmpl
  charts/stable/home-assistant/values.yaml
Labels: kind:incomplete-pr
