Repository k8s-at-home/charts, pull requests merged in 2021-09, with the labels that each got.

#1141 [changedetection-io] Adding chart
  charts/incubator/changedetection-io/.helmignore
  charts/incubator/changedetection-io/Chart.yaml
  charts/incubator/changedetection-io/README.md
  charts/incubator/changedetection-io/README.md.gotmpl
  charts/incubator/changedetection-io/README_CHANGELOG.md.gotmpl
  charts/incubator/changedetection-io/README_CONFIG.md.gotmpl
  charts/incubator/changedetection-io/templates/NOTES.txt
  charts/incubator/changedetection-io/templates/common.yaml
  charts/incubator/changedetection-io/values.yaml
Labels: new chart, precommit:ok, install:ok, lint:ok

#1143 [wmbusmeters] Adding wmbusmeters chart
  charts/stable/wmbusmeters/.helmignore
  charts/stable/wmbusmeters/Chart.yaml
  charts/stable/wmbusmeters/README.md
  charts/stable/wmbusmeters/README.md.gotmpl
  charts/stable/wmbusmeters/README_CHANGELOG.md.gotmpl
  charts/stable/wmbusmeters/README_CONFIG.md.gotmpl
  charts/stable/wmbusmeters/templates/NOTES.txt
  charts/stable/wmbusmeters/templates/common.yaml
  charts/stable/wmbusmeters/templates/configmap.yaml
  charts/stable/wmbusmeters/values.yaml
Labels: new chart, precommit:ok, install:ok, lint:ok

#1152 [speedtest-exporter] switch to serviceMonitor instead of podMonitor
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/README.md
  charts/stable/speedtest-exporter/README_CHANGELOG.md.gotmpl
  charts/stable/speedtest-exporter/templates/podmonitor.yaml
  charts/stable/speedtest-exporter/templates/servicemonitor.yaml
  charts/stable/speedtest-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1154 [games-on-whales] Add env variables for Nvidia
  charts/stable/games-on-whales/Chart.yaml
  charts/stable/games-on-whales/README.md
  charts/stable/games-on-whales/README_CHANGELOG.md.gotmpl
  charts/stable/games-on-whales/README_CONFIG.md.gotmpl
  charts/stable/games-on-whales/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok

#1153 [qbittorrent] add podMonitor and ability to add exporter as a sidecar
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/README.md
  charts/stable/qbittorrent/README_CHANGELOG.md.gotmpl
  charts/stable/qbittorrent/templates/common.yaml
  charts/stable/qbittorrent/templates/podmonitor.yaml
  charts/stable/qbittorrent/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1155 [lidarr] refactor of exportarr sidecar and podmonitor
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/README_CHANGELOG.md.gotmpl
  charts/stable/lidarr/ci/ct-exportarr-values.yaml
  charts/stable/lidarr/templates/common.yaml
  charts/stable/lidarr/templates/podmonitor.yaml
  charts/stable/lidarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1157 [sonarr] refactor of exportarr sidecar and podmonitor
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/README_CHANGELOG.md.gotmpl
  charts/stable/sonarr/ci/ct-exportarr-values.yaml
  charts/stable/sonarr/templates/common.yaml
  charts/stable/sonarr/templates/podmonitor.yaml
  charts/stable/sonarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1156 [radarr] refactor of exportarr sidecar and podmonitor
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/README_CHANGELOG.md.gotmpl
  charts/stable/radarr/ci/ct-exportarr-values.yaml
  charts/stable/radarr/templates/common.yaml
  charts/stable/radarr/templates/podmonitor.yaml
  charts/stable/radarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1158 [lidarr] version bump
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
Labels: precommit:ok, install:ok, lint:ok

#1162 [speedtest-exporter] metrics consistency
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/README.md
  charts/stable/speedtest-exporter/templates/servicemonitor.yaml
  charts/stable/speedtest-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1163 [promcord] move to servicemonitor
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/README.md
  charts/stable/promcord/README_CHANGELOG.md.gotmpl
  charts/stable/promcord/templates/podmonitor.yaml
  charts/stable/promcord/templates/servicemonitor.yaml
  charts/stable/promcord/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1164 [qbittorrent] switch to serviceMonitor
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/README.md
  charts/stable/qbittorrent/README_CHANGELOG.md.gotmpl
  charts/stable/qbittorrent/templates/common.yaml
  charts/stable/qbittorrent/templates/podmonitor.yaml
  charts/stable/qbittorrent/templates/servicemonitor.yaml
  charts/stable/qbittorrent/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1168 [qbittorrent] fix service monitor port
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/README.md
  charts/stable/qbittorrent/templates/servicemonitor.yaml
Labels: precommit:ok, install:ok, lint:ok

#1159 [network-ups-tools] add exporter sidecar
  charts/stable/network-ups-tools/Chart.yaml
  charts/stable/network-ups-tools/README.md
  charts/stable/network-ups-tools/README_CHANGELOG.md.gotmpl
  charts/stable/network-ups-tools/templates/common.yaml
  charts/stable/network-ups-tools/templates/servicemonitor.yaml
  charts/stable/network-ups-tools/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1160 [prometheus-nut-exporter] metrics consistency
  charts/stable/prometheus-nut-exporter/Chart.yaml
  charts/stable/prometheus-nut-exporter/README.md
  charts/stable/prometheus-nut-exporter/templates/common.yaml
  charts/stable/prometheus-nut-exporter/templates/servicemonitor.yaml
  charts/stable/prometheus-nut-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1169 [multus] Avoid hang on upgrade
  charts/stable/multus/Chart.yaml
  charts/stable/multus/README.md
  charts/stable/multus/README_CHANGELOG.md.gotmpl
  charts/stable/multus/templates/uninstallJob.yaml
Labels: precommit:ok, install:ok, lint:ok

#1171 [home-assistant] update hass documentation for running behind a reverse proxy
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok

#1170 [frigate] update default database path in configmap
  charts/stable/frigate/Chart.yaml
  charts/stable/frigate/README.md
  charts/stable/frigate/README_CONFIG.md.gotmpl
  charts/stable/frigate/ci/ct-values.yaml
  charts/stable/frigate/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1173 [cryptofolio] Add chart
  charts/stable/cryptofolio/.helmignore
  charts/stable/cryptofolio/Chart.yaml
  charts/stable/cryptofolio/README.md
  charts/stable/cryptofolio/README.md.gotmpl
  charts/stable/cryptofolio/README_CHANGELOG.md.gotmpl
  charts/stable/cryptofolio/README_CONFIG.md.gotmpl
  charts/stable/cryptofolio/templates/NOTES.txt
  charts/stable/cryptofolio/templates/common.yaml
  charts/stable/cryptofolio/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1172 [blocky] metrics refactor
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/README_CHANGELOG.md.gotmpl
  charts/stable/blocky/templates/prometheusrules.yaml
  charts/stable/blocky/templates/servicemonitor.yaml
  charts/stable/blocky/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1174 [onedrive] Add Chart
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/README.md
  charts/stable/onedrive/README.md.gotmpl
  charts/stable/onedrive/README_CHANGELOG.md.gotmpl
  charts/stable/onedrive/README_CONFIG.md.gotmpl
  charts/stable/onedrive/ci/ct-values.yaml
  charts/stable/onedrive/templates/NOTES.txt
  charts/stable/onedrive/templates/common.yaml
  charts/stable/onedrive/templates/configmap.yaml
  charts/stable/onedrive/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1175 [adguard-home] remove metrics references
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/README_CHANGELOG.md.gotmpl
  charts/stable/adguard-home/templates/servicemonitor.yaml
  charts/stable/adguard-home/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1179 [promcord] metrics refactor
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/README.md
  charts/stable/promcord/README_CHANGELOG.md.gotmpl
  charts/stable/promcord/templates/prometheusrules.yaml
  charts/stable/promcord/templates/servicemonitor.yaml
  charts/stable/promcord/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1184 [lidarr] metrics refactor
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/README_CHANGELOG.md.gotmpl
  charts/stable/lidarr/templates/common.yaml
  charts/stable/lidarr/templates/podmonitor.yaml
  charts/stable/lidarr/templates/prometheusrules.yaml
  charts/stable/lidarr/templates/servicemonitor.yaml
  charts/stable/lidarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1186 [sonarr] metrics refactor
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/README_CHANGELOG.md.gotmpl
  charts/stable/sonarr/templates/common.yaml
  charts/stable/sonarr/templates/podmonitor.yaml
  charts/stable/sonarr/templates/prometheusrules.yaml
  charts/stable/sonarr/templates/servicemonitor.yaml
  charts/stable/sonarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1176 [home-assistant] metrics refactor
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/README_CHANGELOG.md.gotmpl
  charts/stable/home-assistant/templates/prometheusrules.yaml
  charts/stable/home-assistant/templates/servicemonitor.yaml
  charts/stable/home-assistant/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1185 [radarr] metrics refactor
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/README_CHANGELOG.md.gotmpl
  charts/stable/radarr/templates/common.yaml
  charts/stable/radarr/templates/podmonitor.yaml
  charts/stable/radarr/templates/prometheusrules.yaml
  charts/stable/radarr/templates/servicemonitor.yaml
  charts/stable/radarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1189 [lidarr] add template to rules
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1190 [home-assistant] add template to rules
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1191 [radarr] add template to rules
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1192 [sonarr] add template to rules
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1188 [blocky] add template to rules
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1193 [promcord] add template to rules
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/README.md
  charts/stable/promcord/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1187 [onedrive] Corrections from testing to make the experience more seamless
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/README.md
  charts/stable/onedrive/README_CHANGELOG.md.gotmpl
  charts/stable/onedrive/README_CONFIG.md.gotmpl
  charts/stable/onedrive/ci/ct-values.yaml
  charts/stable/onedrive/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1183 [speedtest-exporter] metrics refactor
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/README.md
  charts/stable/speedtest-exporter/README_CHANGELOG.md.gotmpl
  charts/stable/speedtest-exporter/templates/prometheusrules.yaml
  charts/stable/speedtest-exporter/templates/servicemonitor.yaml
  charts/stable/speedtest-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1182 [unifi-poller] metrics refactor
  charts/stable/unifi-poller/Chart.yaml
  charts/stable/unifi-poller/README.md
  charts/stable/unifi-poller/README_CHANGELOG.md.gotmpl
  charts/stable/unifi-poller/templates/prometheusrules.yaml
  charts/stable/unifi-poller/templates/servicemonitor.yaml
  charts/stable/unifi-poller/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1178 [network-ups-tools] metrics refactor
  charts/stable/network-ups-tools/Chart.yaml
  charts/stable/network-ups-tools/README.md
  charts/stable/network-ups-tools/README_CHANGELOG.md.gotmpl
  charts/stable/network-ups-tools/templates/common.yaml
  charts/stable/network-ups-tools/templates/prometheusrules.yaml
  charts/stable/network-ups-tools/templates/servicemonitor.yaml
  charts/stable/network-ups-tools/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1177 [prometheus-nut-exporter] metrics refactor
  charts/stable/prometheus-nut-exporter/Chart.yaml
  charts/stable/prometheus-nut-exporter/README.md
  charts/stable/prometheus-nut-exporter/README_CHANGELOG.md.gotmpl
  charts/stable/prometheus-nut-exporter/templates/prometheusrules.yaml
  charts/stable/prometheus-nut-exporter/templates/servicemonitor.yaml
  charts/stable/prometheus-nut-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1181 [uptime-robot] metrics refactor
  charts/stable/uptimerobot-prometheus/Chart.yaml
  charts/stable/uptimerobot-prometheus/README.md
  charts/stable/uptimerobot-prometheus/README_CHANGELOG.md.gotmpl
  charts/stable/uptimerobot-prometheus/templates/prometheusrules.yaml
  charts/stable/uptimerobot-prometheus/templates/servicemonitor.yaml
  charts/stable/uptimerobot-prometheus/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1194 [lidarr] fix rules
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1195 [home-assistant] fix rules
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1196 [sonarr] fix rules
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1197 [radarr] fix rules
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1198 [promcord] fix rules
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/README.md
  charts/stable/promcord/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1199 [speedtest-exporter] fix rules
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/README.md
  charts/stable/speedtest-exporter/templates/prometheusrules.yaml
  charts/stable/speedtest-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1201 [blocky] fix rules
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/templates/prometheusrules.yaml
Labels: precommit:ok, install:ok, lint:ok

#1202 [onedrive] Move to v2.0.1 of custom docker image
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/README.md
  charts/stable/onedrive/README_CHANGELOG.md.gotmpl
  charts/stable/onedrive/README_CONFIG.md.gotmpl
  charts/stable/onedrive/ci/ct-values.yaml
  charts/stable/onedrive/templates/common.yaml
  charts/stable/onedrive/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1203 [onedrive] Sync appVersion with reality
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/README.md
Labels: precommit:ok, install:ok, lint:ok

#1205 [valheim] Update to use ghcr for image
  charts/stable/valheim/Chart.yaml
  charts/stable/valheim/README.md
  charts/stable/valheim/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1207 [zwavejs2mqtt] Add websocket service
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/README.md
  charts/stable/zwavejs2mqtt/README_CHANGELOG.md.gotmpl
  charts/stable/zwavejs2mqtt/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1206 [unifi] Move traefik serversscheme annotations to service
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/README.md
  charts/stable/unifi/README_CHANGELOG.md.gotmpl
  charts/stable/unifi/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1209 [jackett] Uplifted Jackett version to v0.18.791
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/README.md
  charts/stable/jackett/README_CHANGELOG.md.gotmpl
  charts/stable/jackett/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1212 [overleaf] New chart
  charts/stable/overleaf/.helmignore
  charts/stable/overleaf/Chart.yaml
  charts/stable/overleaf/README.md
  charts/stable/overleaf/README.md.gotmpl
  charts/stable/overleaf/README_CHANGELOG.md.gotmpl
  charts/stable/overleaf/README_CONFIG.md.gotmpl
  charts/stable/overleaf/ci/ct-values.yaml
  charts/stable/overleaf/templates/NOTES.txt
  charts/stable/overleaf/templates/common.yaml
  charts/stable/overleaf/values.yaml
Labels: enhancement, new chart, precommit:ok, install:ok, lint:ok

#1211 [airsonic] Adjust airsonic mount paths for airsonic-advanced
  charts/stable/airsonic/Chart.yaml
  charts/stable/airsonic/README.md
  charts/stable/airsonic/README_CHANGELOG.md.gotmpl
  charts/stable/airsonic/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1214 [aria2] Add Chart
  charts/stable/aria2/.helmignore
  charts/stable/aria2/Chart.yaml
  charts/stable/aria2/README.md
  charts/stable/aria2/README.md.gotmpl
  charts/stable/aria2/README_CHANGELOG.md.gotmpl
  charts/stable/aria2/README_CONFIG.md.gotmpl
  charts/stable/aria2/templates/NOTES.txt
  charts/stable/aria2/templates/common.yaml
  charts/stable/aria2/values.yaml
Labels: precommit:ok, install:ok, lint:ok
