Repository k8s-at-home/charts, pull requests merged in 2022-04, with the labels that each got.

#1495 [home-assistant] image update to 2022.4.0
  charts/stable/home-assistant/Chart.yaml
Labels: size/XS

#1498 [zalando-postgres-cluster] improve docs
  charts/stable/zalando-postgres-cluster/Chart.yaml
  charts/stable/zalando-postgres-cluster/README.md
  charts/stable/zalando-postgres-cluster/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1499 [theme-park] add new chart for theme-park
  charts/stable/theme-park/.helmignore
  charts/stable/theme-park/Chart.yaml
  charts/stable/theme-park/README.md
  charts/stable/theme-park/README_CONFIG.md.gotmpl
  charts/stable/theme-park/templates/NOTES.txt
  charts/stable/theme-park/templates/common.yaml
  charts/stable/theme-park/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1496 [paperless] Updated values.yaml to add user/pass env
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1501 feat: Add kah-common-chart
  .github/ct-install.yaml
  charts/incubator/kah-common-chart/.helmignore
  charts/incubator/kah-common-chart/Chart.yaml
  charts/incubator/kah-common-chart/README_CONFIG.md.gotmpl
  charts/incubator/kah-common-chart/templates/common.yaml
  charts/incubator/kah-common-chart/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1502 feat: Update Unifi to v7
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1500 [factorio]: add chart for factorio server
  .github/ct-install.yaml
  charts/stable/factorio/.helmignore
  charts/stable/factorio/Chart.yaml
  charts/stable/factorio/README.md
  charts/stable/factorio/README_CONFIG.md.gotmpl
  charts/stable/factorio/templates/NOTES.txt
  charts/stable/factorio/templates/common.yaml
  charts/stable/factorio/templates/configmap.yaml
  charts/stable/factorio/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1506 uptime-kuma: update appVersion to 1.14.0
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1509 [sonarr] Uplifted Sonarr version to v3.0.7.1477
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1513 [radarr] Updated docker image to version v4.1.0.6175
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1510 [qbittorrent] Updated Docker image to v4.4.2
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/README.md
  charts/stable/qbittorrent/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1512 [jackett] Update jackett docker image to v0.20.892
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/README.md
  charts/stable/jackett/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1511 [bazarr] Updated Docker image to v1.0.3
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/README.md
  charts/stable/bazarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1508 [Plex] Update Plex image to v1.25.9.5721-965587f64
  charts/stable/plex/Chart.yaml
  charts/stable/plex/README.md
  charts/stable/plex/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1521 [homeassistant] fix pvc for postgresql
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1522 [miniflux] Upgrade miniflux to version 2.0.36
  charts/stable/miniflux/Chart.yaml
  charts/stable/miniflux/README.md
  charts/stable/miniflux/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1507 [dendrite] Update to v0.8.1
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/templates/common.yaml
  charts/incubator/dendrite/templates/dendrite-config.yaml
  charts/incubator/dendrite/templates/postgresql-initdb.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1526 [prowlarr] Uplifted the docker image to use the latest nightly release
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/README.md
  charts/stable/prowlarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1528 [Plex] update image to v1.26.0.5715-8cf78dab3
  charts/stable/plex/Chart.yaml
  charts/stable/plex/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1530 uptime-kuma: update appVersion to 1.15.0
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1531 [audiobookshelf] Bump app version and change default image repo to ghcr
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/README.md
  charts/stable/audiobookshelf/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1515 [nightscout] Add chart nightscout
  charts/stable/nightscout/.helmignore
  charts/stable/nightscout/Chart.yaml
  charts/stable/nightscout/README.md
  charts/stable/nightscout/README_CONFIG.md.gotmpl
  charts/stable/nightscout/templates/NOTES.txt
  charts/stable/nightscout/templates/common.yaml
  charts/stable/nightscout/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1532 paperless: Update appVersion to 1.7.0
  charts/stable/paperless/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1527 [tdarr] Pass-through mountPath value
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1534 [homebridge] Update image
  charts/stable/homebridge/Chart.yaml
  charts/stable/homebridge/templates/common.yaml
  charts/stable/homebridge/templates/configmap.yaml
  charts/stable/homebridge/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1536 uptime-kuma: update appVersion to 1.15.1
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1539 [paperles] Set PAPERLES_URL automatically
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/README.md
  charts/stable/paperless/templates/common.yaml
  charts/stable/paperless/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1540 [pod-gateway] Change default openvpn port to 1194
  charts/stable/pod-gateway/Chart.yaml
  charts/stable/pod-gateway/README.md
  charts/stable/pod-gateway/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S
