Repository k8s-at-home/charts, pull requests merged in 2022-01, with the labels that each got.

#1347 [webtrees] Add new chart
  charts/stable/webtrees/.helmignore
  charts/stable/webtrees/Chart.yaml
  charts/stable/webtrees/README.md
  charts/stable/webtrees/README.md.gotmpl
  charts/stable/webtrees/README_CHANGELOG.md.gotmpl
  charts/stable/webtrees/README_CONFIG.md.gotmpl
  charts/stable/webtrees/ci/ct-values.yaml
  charts/stable/webtrees/templates/NOTES.txt
  charts/stable/webtrees/templates/common.yaml
  charts/stable/webtrees/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1348 [facebox] Exclude from autotest install phase
  .github/ct-install.yaml
Labels: precommit:ok

#1349 [home-assistant] Update postgresql, dependencies
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/README_CHANGELOG.md.gotmpl
  charts/stable/home-assistant/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1315 [facebox] initial release
  charts/stable/facebox/.helmignore
  charts/stable/facebox/Chart.yaml
  charts/stable/facebox/README.md
  charts/stable/facebox/README.md.gotmpl
  charts/stable/facebox/README_CHANGELOG.md.gotmpl
  charts/stable/facebox/README_CONFIG.md.gotmpl
  charts/stable/facebox/templates/NOTES.txt
  charts/stable/facebox/templates/common.yaml
  charts/stable/facebox/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1319 [dendrite] Add dendrite helm chart
  charts/incubator/dendrite/.helmignore
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/README.md
  charts/incubator/dendrite/README.md.gotmpl
  charts/incubator/dendrite/README_CHANGELOG.md.gotmpl
  charts/incubator/dendrite/README_CONFIG.md.gotmpl
  charts/incubator/dendrite/ci/ct-values.yaml
  charts/incubator/dendrite/templates/NOTES.txt
  charts/incubator/dendrite/templates/common.yaml
  charts/incubator/dendrite/templates/dendrite-config.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1352 [node-red] Upgrade to 2.1.4.
  charts/stable/node-red/Chart.yaml
  charts/stable/node-red/README.md
  charts/stable/node-red/README_CHANGELOG.md.gotmpl
  charts/stable/node-red/values.yaml
Labels: precommit:ok

#1354 [ci] Update Readme CI
  .github/ct-lint.yaml
  .github/workflows/charts-lint-test.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/generate-readme.yaml
  .github/workflows/generate-renovate-changelog.yaml
  charts/incubator/seafile/Chart.yaml
  charts/incubator/seafile/README.md
  charts/incubator/seafile/README.md.gotmpl
  charts/incubator/seafile/README_CHANGELOG.md.gotmpl
  hack/check-releasenotes.sh
  hack/gen-helm-docs.sh
  hack/renovate-releasenotes.sh
  hack/templates/README.md.gotmpl
  hack/templates/README_CHANGELOG.md.gotmpl
  templates/chart/Chart.yaml
  templates/chart/README.md
  templates/chart/README.md.gotmpl
  templates/chart/README_CHANGELOG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok

#1359 [ghost] Fix PVC creation
  .github/workflows/charts-validate.yaml
  charts/stable/ghost/Chart.yaml
  charts/stable/ghost/README.md
  charts/stable/ghost/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok

#1361 [privatebin] Add privatebin helm chart
  charts/stable/privatebin/.helmignore
  charts/stable/privatebin/Chart.yaml
  charts/stable/privatebin/README.md
  charts/stable/privatebin/README.md.gotmpl
  charts/stable/privatebin/README_CONFIG.md.gotmpl
  charts/stable/privatebin/templates/NOTES.txt
  charts/stable/privatebin/templates/common.yaml
  charts/stable/privatebin/templates/configmap.yaml
  charts/stable/privatebin/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1368 [dendrite] Fix postgresql init scripts for dendrite
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/README.md
  charts/incubator/dendrite/templates/common.yaml
  charts/incubator/dendrite/templates/postgresql-initdb.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1371 [dokuwiki] Add dokuwiki helm chart
  charts/stable/dokuwiki/.helmignore
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/README.md
  charts/stable/dokuwiki/README.md.gotmpl
  charts/stable/dokuwiki/README_CONFIG.md.gotmpl
  charts/stable/dokuwiki/templates/NOTES.txt
  charts/stable/dokuwiki/templates/common.yaml
  charts/stable/dokuwiki/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1374 [deconz] Update repository/tag and config mountPath
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/README.md
  charts/stable/deconz/values.yaml
Labels: kind:incomplete-docs, precommit:ok, install:ok, lint:ok

#1373 [powerdns-admin] initial release of powerdns-admin frontend
  charts/stable/powerdns-admin/.helmignore
  charts/stable/powerdns-admin/Chart.yaml
  charts/stable/powerdns-admin/README.md
  charts/stable/powerdns-admin/README.md.gotmpl
  charts/stable/powerdns-admin/README_CONFIG.md.gotmpl
  charts/stable/powerdns-admin/templates/NOTES.txt
  charts/stable/powerdns-admin/templates/common.yaml
  charts/stable/powerdns-admin/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1379 [radicale] Add new chart
  charts/stable/radicale/.helmignore
  charts/stable/radicale/Chart.yaml
  charts/stable/radicale/README.md
  charts/stable/radicale/README.md.gotmpl
  charts/stable/radicale/README_CONFIG.md.gotmpl
  charts/stable/radicale/ci/ct-values.yaml
  charts/stable/radicale/templates/NOTES.txt
  charts/stable/radicale/templates/common.yaml
  charts/stable/radicale/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1383 [unifi] Upgraded unifi image to version 6.5.55.
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/README.md
  charts/stable/unifi/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1385 [ghost] Fix database string to match generated svc
  charts/stable/ghost/Chart.yaml
  charts/stable/ghost/README.md
  charts/stable/ghost/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1386 [maddy] Initial release
  charts/stable/maddy/.helmignore
  charts/stable/maddy/Chart.yaml
  charts/stable/maddy/README.md
  charts/stable/maddy/README.md.gotmpl
  charts/stable/maddy/README_CONFIG.md.gotmpl
  charts/stable/maddy/ci/ct-values.yaml
  charts/stable/maddy/files/maddy.conf
  charts/stable/maddy/files/smtp_rules/default.conf
  charts/stable/maddy/templates/NOTES.txt
  charts/stable/maddy/templates/common.yaml
  charts/stable/maddy/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1388 [torrserver] Chart init
  charts/incubator/torrserver/.helmignore
  charts/incubator/torrserver/Chart.yaml
  charts/incubator/torrserver/README.md
  charts/incubator/torrserver/README.md.gotmpl
  charts/incubator/torrserver/README_CONFIG.md.gotmpl
  charts/incubator/torrserver/templates/NOTES.txt
  charts/incubator/torrserver/templates/common.yaml
  charts/incubator/torrserver/values.yaml
Labels: precommit:ok, install:ok, lint:ok

#1391 [maddy] enable configuring storage and imap
  charts/stable/maddy/Chart.yaml
  charts/stable/maddy/README.md
  charts/stable/maddy/files/maddy.conf
  charts/stable/maddy/templates/common.yaml
  charts/stable/maddy/values.yaml
Labels: precommit:ok, install:ok, lint:ok
