Repository k8s-at-home/charts, pull requests merged in 2022-05, with the labels that each got.

#1547 [paperless] Add http(s) prefix to PAPERLESS_URL
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/README.md
  charts/stable/paperless/templates/common.yaml
Labels: size/XS

#1560 [onedrive] Update docker image to v2.4.17
  charts/stable/onedrive/Chart.yaml
  charts/stable/onedrive/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1559 [satisfactory] - feat: add satisfactory helm
  .github/ct-install.yaml
  charts/stable/satisfactory/.helmignore
  charts/stable/satisfactory/Chart.yaml
  charts/stable/satisfactory/README.md
  charts/stable/satisfactory/README_CONFIG.md.gotmpl
  charts/stable/satisfactory/templates/NOTES.txt
  charts/stable/satisfactory/templates/common.yaml
  charts/stable/satisfactory/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1561 [blocky] - Add redis
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/README.md
  charts/stable/blocky/README_CONFIG.md.gotmpl
  charts/stable/blocky/ci/ct-values.yaml
  charts/stable/blocky/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1568 [vikunja] Fix subpath in configmap to match persistence value
  charts/stable/vikunja/Chart.yaml
  charts/stable/vikunja/templates/configmap.yaml
  charts/stable/vikunja/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1563 [home-assistant] Add disabled codeserver addon to values.
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/README.md
  charts/stable/home-assistant/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1567 [syslog-ng] Add syslog-ng Chart
  charts/stable/syslog-ng/.helmignore
  charts/stable/syslog-ng/Chart.yaml
  charts/stable/syslog-ng/README.md
  charts/stable/syslog-ng/README_CONFIG.md.gotmpl
  charts/stable/syslog-ng/templates/NOTES.txt
  charts/stable/syslog-ng/templates/common.yaml
  charts/stable/syslog-ng/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1573 feat!: Deprecation of truecommand, traccar, reg, powerdns, piaware, projector charts
  charts/stable/jetbrains-projector/Chart.yaml
  charts/stable/piaware/Chart.yaml
  charts/stable/powerdns/Chart.yaml
  charts/stable/reg/Chart.yaml
  charts/stable/traccar/Chart.yaml
  charts/stable/truecommand/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1574 feat!: Removal of truecommand, traccar, reg, powerdns, piaware, projector charts
  charts/stable/jetbrains-projector/Chart.yaml
  charts/stable/jetbrains-projector/README.md
  charts/stable/jetbrains-projector/README_CONFIG.md.gotmpl
  charts/stable/jetbrains-projector/ci/ct-values.yaml
  charts/stable/jetbrains-projector/templates/NOTES.txt
  charts/stable/jetbrains-projector/templates/_helpers.tpl
  charts/stable/jetbrains-projector/templates/common.yaml
  charts/stable/jetbrains-projector/templates/configmap.yaml
  charts/stable/jetbrains-projector/templates/secret.yaml
  charts/stable/jetbrains-projector/values.yaml
  charts/stable/piaware/.helmignore
  charts/stable/piaware/Chart.yaml
  charts/stable/piaware/README.md
  charts/stable/piaware/README_CONFIG.md.gotmpl
  charts/stable/piaware/ci/ct-values.yaml
  charts/stable/piaware/templates/NOTES.txt
  charts/stable/piaware/templates/common.yaml
  charts/stable/piaware/values.yaml
  charts/stable/powerdns/.helmignore
  charts/stable/powerdns/Chart.yaml
  charts/stable/powerdns/README.md
  charts/stable/powerdns/README_CONFIG.md.gotmpl
  charts/stable/powerdns/templates/NOTES.txt
  charts/stable/powerdns/templates/_helpers.tpl
  charts/stable/powerdns/templates/configmap.yaml
  charts/stable/powerdns/templates/deployment.yaml
  charts/stable/powerdns/templates/secret.yaml
  charts/stable/powerdns/templates/service.yaml
  charts/stable/powerdns/templates/serviceaccount.yaml
  charts/stable/powerdns/values.yaml
  charts/stable/reg/.helmignore
  charts/stable/reg/Chart.yaml
  charts/stable/reg/README.md
  charts/stable/reg/README_CONFIG.md.gotmpl
  charts/stable/reg/ci/ct-values.yaml
  charts/stable/reg/templates/NOTES.txt
  charts/stable/reg/templates/common.yaml
  charts/stable/reg/values.yaml
  charts/stable/traccar/.helmignore
  charts/stable/traccar/Chart.yaml
  charts/stable/traccar/README.md
  charts/stable/traccar/README_CONFIG.md.gotmpl
  charts/stable/traccar/templates/NOTES.txt
  charts/stable/traccar/templates/common.yaml
  charts/stable/traccar/values.yaml
  charts/stable/truecommand/.helmignore
  charts/stable/truecommand/Chart.yaml
  charts/stable/truecommand/README.md
  charts/stable/truecommand/README_CONFIG.md.gotmpl
  charts/stable/truecommand/templates/NOTES.txt
  charts/stable/truecommand/templates/common.yaml
  charts/stable/truecommand/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XXL

#1575 [ombi] Upgraded application image version to 4.16.12
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/README.md
  charts/stable/ombi/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1566 [autobrr] Update app description
  charts/stable/autobrr/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1578 [Plex] update image to v1.26.1.5798-99a4a6ac9
  charts/stable/plex/Chart.yaml
  charts/stable/plex/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1580 [paperless] Bump to version 1.7.1
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1582 [vaultwarden] Bump Vaultwarden App Version to 1.25.0
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/README.md
  charts/stable/vaultwarden/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1576 [firefly-iii] Added firefly-iii chart
  charts/stable/firefly-iii/.helmignore
  charts/stable/firefly-iii/Chart.yaml
  charts/stable/firefly-iii/templates/NOTES.txt
  charts/stable/firefly-iii/templates/common.tpl
  charts/stable/firefly-iii/templates/importer.yaml
  charts/stable/firefly-iii/templates/recurring-cron.yaml
  charts/stable/firefly-iii/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XL

#1579 cryptpad: update cryptpad-docker to v4.14.1-nginx
  charts/incubator/cryptpad/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1586 [send] Added timvisee Send chart
  charts/stable/send/.helmignore
  charts/stable/send/Chart.yaml
  charts/stable/send/README.md
  charts/stable/send/README_CONFIG.md.gotmpl
  charts/stable/send/ci/ct-values.yaml
  charts/stable/send/templates/NOTES.txt
  charts/stable/send/templates/common.yaml
  charts/stable/send/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1587 [mealie] Support mealie v1.0.0
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/templates/common.yaml
  charts/stable/mealie/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1589 uptime-kuma: update to 1.16.1
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:failed, changelog:ok, size/XS

#1591 [mealie] Fix loading environment variables for backend
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS
