Repository k8s-at-home/charts, pull requests merged in 2022-06, with the labels that each got.

#1592 [handbrake] initial contribution
  charts/incubator/handbrake/.helmignore
  charts/incubator/handbrake/Chart.yaml
  charts/incubator/handbrake/README.md
  charts/incubator/handbrake/README_CONFIG.md.gotmpl
  charts/incubator/handbrake/templates/NOTES.txt
  charts/incubator/handbrake/templates/common.yaml
  charts/incubator/handbrake/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1581 [dendrite] Per-component database settings
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/templates/dendrite-config.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1601 chore: bump unifi to v7.1.66
  charts/stable/unifi/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1569 [gatus] Add gatus chart
  charts/stable/gatus/.helmignore
  charts/stable/gatus/Chart.yaml
  charts/stable/gatus/README_CONFIG.md.gotmpl
  charts/stable/gatus/templates/common.yaml
  charts/stable/gatus/values.yaml
Labels: precommit:ok, install:failed, lint:ok, changelog:ok, size/M

#1584 [mqtt-exporter] Add new chart
  charts/stable/mqtt-exporter/.helmignore
  charts/stable/mqtt-exporter/Chart.yaml
  charts/stable/mqtt-exporter/README.md
  charts/stable/mqtt-exporter/README_CONFIG.md.gotmpl
  charts/stable/mqtt-exporter/ci/ct-values.yaml
  charts/stable/mqtt-exporter/templates/NOTES.txt
  charts/stable/mqtt-exporter/templates/common.yaml
  charts/stable/mqtt-exporter/templates/servicemonitor.yaml
  charts/stable/mqtt-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1604 [rutorrent] add chart
  charts/stable/rtorrent-rutorrent/.helmignore
  charts/stable/rtorrent-rutorrent/Chart.yaml
  charts/stable/rtorrent-rutorrent/README.md
  charts/stable/rtorrent-rutorrent/README_CONFIG.md.gotmpl
  charts/stable/rtorrent-rutorrent/templates/NOTES.txt
  charts/stable/rtorrent-rutorrent/templates/common.yaml
  charts/stable/rtorrent-rutorrent/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1606 [mealie] Fix quoting of mealie environment variables
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1607 [gatus] fix config volume
  charts/stable/gatus/Chart.yaml
  charts/stable/gatus/README.md
  charts/stable/gatus/templates/common.yaml
  charts/stable/gatus/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1611 chore: fix unifi podsecurity context
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1616 [mopidy] Add new chart
  charts/incubator/mopidy/.helmignore
  charts/incubator/mopidy/Chart.yaml
  charts/incubator/mopidy/README.md
  charts/incubator/mopidy/README_CONFIG.md.gotmpl
  charts/incubator/mopidy/templates/NOTES.txt
  charts/incubator/mopidy/templates/common.yaml
  charts/incubator/mopidy/templates/configmap.yaml
  charts/incubator/mopidy/values.yaml
  templates/chart/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1615 [snapcast] Adding new chart
  charts/incubator/snapcast/.helmignore
  charts/incubator/snapcast/Chart.yaml
  charts/incubator/snapcast/README.md
  charts/incubator/snapcast/README_CONFIG.md.gotmpl
  charts/incubator/snapcast/templates/NOTES.txt
  charts/incubator/snapcast/templates/common.yaml
  charts/incubator/snapcast/templates/configmap.yaml
  charts/incubator/snapcast/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1623 [mosquitto] Add per_listener_settings option
  charts/stable/mosquitto/Chart.yaml
  charts/stable/mosquitto/templates/configmap.yaml
  charts/stable/mosquitto/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1621 [teamspeak] feat: Can now change metric exporter remote
  charts/incubator/teamspeak/Chart.yaml
  charts/incubator/teamspeak/templates/common.yaml
  charts/incubator/teamspeak/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1627 [photoprism] update image to 220617-jammy
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1628 uptime-kuma: update appVersion to 1.17.0 (chart version 1.3.4)
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1624 [shinobi] Add Shinobi chart
  charts/stable/shinobi/.helmignore
  charts/stable/shinobi/Chart.yaml
  charts/stable/shinobi/README.md
  charts/stable/shinobi/README_CONFIG.md.gotmpl
  charts/stable/shinobi/templates/NOTES.txt
  charts/stable/shinobi/templates/common.yaml
  charts/stable/shinobi/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1629 uptime-kuma: update appVersion to 1.17.1 (chart version 1.3.5)
  charts/stable/uptime-kuma/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1637 [prometheus-nut-exporter] Fix service monitor.
  charts/stable/prometheus-nut-exporter/Chart.yaml
  charts/stable/prometheus-nut-exporter/templates/servicemonitor.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS
