Repository k8s-at-home/charts, pull requests merged in 2022-07, with the labels that each got.

#1679 [Dendrite] Polylith ingress and config fixes
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/ci/polylith-full-values.yaml
  charts/incubator/dendrite/templates/dendrite-config.yaml
  charts/incubator/dendrite/templates/ingress.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1683 [teslamate] Update teslamate postgres persistence values
  charts/stable/teslamate/Chart.yaml
  charts/stable/teslamate/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1688 [pod-gateway]: Bump image versions
  charts/stable/pod-gateway/Chart.yaml
  charts/stable/pod-gateway/templates/common.yaml
  charts/stable/pod-gateway/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1686 [adguard-home] Upgrade to version v0.107.7
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/README.md
  charts/stable/adguard-home/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1680 [deemix] Add Deemix chart
  charts/stable/deemix/.helmignore
  charts/stable/deemix/Chart.yaml
  charts/stable/deemix/README.md
  charts/stable/deemix/README_CONFIG.md.gotmpl
  charts/stable/deemix/templates/NOTES.txt
  charts/stable/deemix/templates/common.yaml
  charts/stable/deemix/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1689 [ntfy] Add ntfy chart
  charts/stable/ntfy/.helmignore
  charts/stable/ntfy/Chart.yaml
  charts/stable/ntfy/README.md
  charts/stable/ntfy/README_CONFIG.md.gotmpl
  charts/stable/ntfy/templates/NOTES.txt
  charts/stable/ntfy/templates/common.yaml
  charts/stable/ntfy/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1690 [tt-rss] Fix env vars
  charts/stable/tt-rss/Chart.yaml
  charts/stable/tt-rss/templates/common.yaml
  charts/stable/tt-rss/values.yaml
Labels: size/S

#1706 [vaultwarden] Update Image/App Version to v1.25.1
  charts/stable/vaultwarden/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1695 [plex] update image to 1.27.2.5929-a806c5905.
  charts/stable/plex/Chart.yaml
  charts/stable/plex/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1693 [node-red] upgrade to 2.2.2
  charts/stable/node-red/Chart.yaml
  charts/stable/node-red/README.md
  charts/stable/node-red/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1702 [mosquitto] Update container image to v2.0.14
  charts/stable/mosquitto/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1705 [jackett] Bumping jackett version to the latest stable version v0.20.1316
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1697 [photoprism] update image to 220629-jammy
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1709 [mosquitto] Use appVersion as image tag by default
  charts/stable/mosquitto/Chart.yaml
  charts/stable/mosquitto/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1715 [vaultwarden] Update Image/App Version to v1.25.2
  charts/stable/vaultwarden/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1714 [anonaddy] Bump AnonAddy Version to 0.12.3
  charts/stable/anonaddy/Chart.yaml
  charts/stable/anonaddy/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1711 [mosquitto] Add option for selectively adding listener
  charts/stable/mosquitto/Chart.yaml
  charts/stable/mosquitto/README.md
  charts/stable/mosquitto/templates/configmap.yaml
  charts/stable/mosquitto/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1718 chore: bump unifi app to v7.1.68
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/README.md
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1719 [homebridge] Bump appVersion to 2022-07-08
  charts/stable/homebridge/Chart.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS
