Repository k8s-at-home/charts, pull requests merged in 2022-03, with the labels that each got.

#1436 [paperless] chore: switch to paperless-ngx project
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/README.md
  charts/stable/paperless/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1439 [ghost]: Upgrade appversion to 4.37.0
  charts/stable/ghost/Chart.yaml
  charts/stable/ghost/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1441 [photoprism] Add MariaDB support to Photoprism
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/README.md
  charts/stable/photoprism/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1442 [warrior] New incubator chart for ArchiveTeam warrior
  charts/incubator/warrior/.helmignore
  charts/incubator/warrior/Chart.yaml
  charts/incubator/warrior/README_CONFIG.md.gotmpl
  charts/incubator/warrior/templates/NOTES.txt
  charts/incubator/warrior/templates/common.yaml
  charts/incubator/warrior/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1446 [home-assistant] Upgrade app to 2022.3.2
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1450 [paperless] feat: upgrade to paperless-ngx 1.6.0
  charts/stable/paperless/Chart.yaml
  charts/stable/paperless/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1449 [signalclirestapi] Add incubator chart signal-cli-rest-api
  charts/incubator/signal-cli-rest-api/.helmignore
  charts/incubator/signal-cli-rest-api/Chart.yaml
  charts/incubator/signal-cli-rest-api/README.md
  charts/incubator/signal-cli-rest-api/README_CONFIG.md.gotmpl
  charts/incubator/signal-cli-rest-api/templates/NOTES.txt
  charts/incubator/signal-cli-rest-api/templates/common.yaml
  charts/incubator/signal-cli-rest-api/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1451 [dendrite] Fix image tag not followed in polylith
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/templates/common.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1452 [mealie] Remove deprecated env and update app version
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1447 [otel-collector] add open telemetry collector with example config
  .taskfiles/Taskfile_chart.yml
  charts/stable/otel-collector/.helmignore
  charts/stable/otel-collector/Chart.yaml
  charts/stable/otel-collector/README.md
  charts/stable/otel-collector/README_CONFIG.md.gotmpl
  charts/stable/otel-collector/templates/NOTES.txt
  charts/stable/otel-collector/templates/common.yaml
  charts/stable/otel-collector/templates/secret.yaml
  charts/stable/otel-collector/templates/servicemonitor.yaml
  charts/stable/otel-collector/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1456 [wikijs] Remove default empty env variables for wikijs - fixes #1455
  charts/stable/wikijs/Chart.yaml
  charts/stable/wikijs/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1460 [monica] Remove default empty env variables - along the same lines as #1455
  charts/stable/monica/Chart.yaml
  charts/stable/monica/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1453 [influxdb-exporter] update img to 0.9.0, use other port for UDP
  charts/stable/influxdb-exporter/Chart.yaml
  charts/stable/influxdb-exporter/templates/servicemonitor.yaml
  charts/stable/influxdb-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1467 [recipes] reverse proxy auth support
  charts/stable/recipes/Chart.yaml
  charts/stable/recipes/README.md
  charts/stable/recipes/templates/configmap.yaml
  charts/stable/recipes/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1459 [kube-ops-view] Add chart for kube-ops-view
  charts/stable/kube-ops-view/.helmignore
  charts/stable/kube-ops-view/Chart.yaml
  charts/stable/kube-ops-view/README.md
  charts/stable/kube-ops-view/README_CONFIG.md.gotmpl
  charts/stable/kube-ops-view/templates/NOTES.txt
  charts/stable/kube-ops-view/templates/common.yaml
  charts/stable/kube-ops-view/templates/rbac.yaml
  charts/stable/kube-ops-view/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1457 [nginx-php] feat: add new chart
  charts/stable/nginx-php/.helmignore
  charts/stable/nginx-php/Chart.yaml
  charts/stable/nginx-php/README.md
  charts/stable/nginx-php/README_CONFIG.md.gotmpl
  charts/stable/nginx-php/ci/ct-values.yaml
  charts/stable/nginx-php/templates/NOTES.txt
  charts/stable/nginx-php/templates/common.yaml
  charts/stable/nginx-php/templates/configmap.yaml
  charts/stable/nginx-php/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1444 [sdtd] Add 7 Days to Die chart.
  .github/ct-install.yaml
  charts/incubator/sdtd/.helmignore
  charts/incubator/sdtd/Chart.yaml
  charts/incubator/sdtd/README.md
  charts/incubator/sdtd/README_CONFIG.md.gotmpl
  charts/incubator/sdtd/templates/NOTES.txt
  charts/incubator/sdtd/templates/common.yaml
  charts/incubator/sdtd/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1466 chore(homebridge): Set permissions for startup.sh to be executable
  charts/stable/homebridge/Chart.yaml
  charts/stable/homebridge/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1482 uptime-kuma: update version to 1.13.1
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1471 [babybuddy] add chart: babybuddy
  charts/incubator/babybuddy/.helmignore
  charts/incubator/babybuddy/Chart.yaml
  charts/incubator/babybuddy/README.md
  charts/incubator/babybuddy/README_CONFIG.md.gotmpl
  charts/incubator/babybuddy/templates/NOTES.txt
  charts/incubator/babybuddy/templates/common.yaml
  charts/incubator/babybuddy/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M
