Repository k8s-at-home/charts, pull requests merged in 2022-02, with the labels that each got.

#1389 [recipes] update tandoor version and adjust default upload size
  charts/stable/recipes/Chart.yaml
  charts/stable/recipes/README.md
  charts/stable/recipes/templates/configmap.yaml
  charts/stable/recipes/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1397 [error-pages] new chart
  charts/stable/error-pages/.helmignore
  charts/stable/error-pages/Chart.yaml
  charts/stable/error-pages/README.md
  charts/stable/error-pages/README.md.gotmpl
  charts/stable/error-pages/README_CONFIG.md.gotmpl
  charts/stable/error-pages/templates/NOTES.txt
  charts/stable/error-pages/templates/common.yaml
  charts/stable/error-pages/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1398 [dendrite] Switch from Kafka to NATS
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/templates/dendrite-config.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1299 [grocy] Upgrade to version 3.1.3 and fix upgrade bug
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/README.md
  charts/stable/grocy/values.yaml
Labels: precommit:ok, install:ok, lint:ok, size/S

#1400 [lidarr/radarr/sonarr]: update exportarr to v1.0.0
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/ci/ct-exportarr-values.yaml
  charts/stable/lidarr/templates/common.yaml
  charts/stable/lidarr/values.yaml
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/ci/ct-exportarr-values.yaml
  charts/stable/radarr/templates/common.yaml
  charts/stable/radarr/values.yaml
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/ci/ct-exportarr-values.yaml
  charts/stable/sonarr/templates/common.yaml
  charts/stable/sonarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1402 [samba] changed samba server docker image
  charts/stable/samba/Chart.yaml
  charts/stable/samba/README.md
  charts/stable/samba/templates/common.yaml
  charts/stable/samba/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1405 [monica] App version bump to 3.7.0-apache.
  charts/stable/monica/Chart.yaml
  charts/stable/monica/README.md
  charts/stable/monica/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1404 [traefik-forward-auth] Reuse existing secret.
  charts/stable/traefik-forward-auth/Chart.yaml
  charts/stable/traefik-forward-auth/ci/ct-values.yaml
  charts/stable/traefik-forward-auth/templates/NOTES.txt
  charts/stable/traefik-forward-auth/templates/_helpers.tpl
  charts/stable/traefik-forward-auth/templates/common.yaml
  charts/stable/traefik-forward-auth/templates/deployment.yaml
  charts/stable/traefik-forward-auth/templates/hpa.yaml
  charts/stable/traefik-forward-auth/templates/ingress.yaml
  charts/stable/traefik-forward-auth/templates/middleware.yaml
  charts/stable/traefik-forward-auth/templates/secret.yaml
  charts/stable/traefik-forward-auth/templates/service.yaml
  charts/stable/traefik-forward-auth/templates/serviceaccount.yaml
  charts/stable/traefik-forward-auth/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1411 [vaultwarden] Upgrade app version to 1.24.0
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/README.md
  charts/stable/vaultwarden/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1410 [dendrite] Bump dendrite app version to v0.6.3
  charts/incubator/dendrite/Chart.yaml
  charts/incubator/dendrite/README.md
  charts/incubator/dendrite/templates/common.yaml
  charts/incubator/dendrite/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1414 [puppeteer] new chart
  charts/stable/puppeteer/.helmignore
  charts/stable/puppeteer/Chart.yaml
  charts/stable/puppeteer/README.md
  charts/stable/puppeteer/README.md.gotmpl
  charts/stable/puppeteer/README_CONFIG.md.gotmpl
  charts/stable/puppeteer/templates/NOTES.txt
  charts/stable/puppeteer/templates/common.yaml
  charts/stable/puppeteer/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1415 [puppeteer] update readme
  charts/stable/puppeteer/Chart.yaml
  charts/stable/puppeteer/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1416 [influxdb-exporter] Add influxdb-exporter chart for Proxmox metric server
  charts/stable/influxdb-exporter/.helmignore
  charts/stable/influxdb-exporter/Chart.yaml
  charts/stable/influxdb-exporter/README.md
  charts/stable/influxdb-exporter/README.md.gotmpl
  charts/stable/influxdb-exporter/README_CONFIG.md.gotmpl
  charts/stable/influxdb-exporter/templates/NOTES.txt
  charts/stable/influxdb-exporter/templates/common.yaml
  charts/stable/influxdb-exporter/templates/servicemonitor.yaml
  charts/stable/influxdb-exporter/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1418 [rtsp-to-web] Add initial revision of RTSPtoWeb helm chart
  charts/stable/rtsp-to-web/.helmignore
  charts/stable/rtsp-to-web/Chart.yaml
  charts/stable/rtsp-to-web/README.md
  charts/stable/rtsp-to-web/README.md.gotmpl
  charts/stable/rtsp-to-web/README_CONFIG.md.gotmpl
  charts/stable/rtsp-to-web/templates/NOTES.txt
  charts/stable/rtsp-to-web/templates/common.yaml
  charts/stable/rtsp-to-web/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1419 [sonarr] add metrics config subpath when config has subPath specified
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/README.md
  charts/stable/sonarr/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1420 [lidarr] add missing metrics subpath when persistence.config.subPath specified
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/README.md
  charts/stable/lidarr/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1421 [radarr] add metrics config subpath when config has subPath specified
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/README.md
  charts/stable/radarr/templates/common.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1424 [miniflux] Upgrade miniflux to version 2.0.35
  charts/stable/miniflux/Chart.yaml
  charts/stable/miniflux/README.md
  charts/stable/miniflux/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1429 Update contributing instructions for breaking changes
  CONTRIBUTING.md
Labels: precommit:ok, install:failed, lint:ok, changelog:ok, size/XS

#1427 [influxdb-exporter] fix README
  charts/stable/influxdb-exporter/Chart.yaml
  charts/stable/influxdb-exporter/README.md
  charts/stable/influxdb-exporter/README_CONFIG.md.gotmpl
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1423 [audiobookshelf] Add audiobookshelf helm chart
  charts/stable/audiobookshelf/.helmignore
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/README.md
  charts/stable/audiobookshelf/README.md.gotmpl
  charts/stable/audiobookshelf/README_CONFIG.md.gotmpl
  charts/stable/audiobookshelf/templates/NOTES.txt
  charts/stable/audiobookshelf/templates/common.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1425 [frigate] Update frigate to 8.0.0
  charts/stable/frigate/Chart.yaml
  charts/stable/frigate/ci/ct-values.yaml
  charts/stable/frigate/templates/common.yaml
  charts/stable/frigate/templates/configmap.yaml
  charts/stable/frigate/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/M

#1432 [tdarr] Add environment variables to change the user running the node
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1426 [strongswan] Add StrongSwan chart.
  charts/incubator/strongswan/.helmignore
  charts/incubator/strongswan/Chart.yaml
  charts/incubator/strongswan/README.md
  charts/incubator/strongswan/README_CONFIG.md.gotmpl
  charts/incubator/strongswan/ci/ct-values.yaml
  charts/incubator/strongswan/templates/NOTES.txt
  charts/incubator/strongswan/templates/common.yaml
  charts/incubator/strongswan/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/L

#1434 [lancache] Add probes for LanCache DNS.
  charts/incubator/lancache/Chart.yaml
  charts/incubator/lancache/templates/common.yaml
  charts/incubator/lancache/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1435 [pod-gateway] Permit overriding DNSPolicy
  charts/stable/pod-gateway/Chart.yaml
  charts/stable/pod-gateway/templates/webhook-deployment.yaml
  charts/stable/pod-gateway/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS

#1428 [rtsp-to-web] Update RTSPtoWeb to 2.2.0 and update config location
  charts/stable/rtsp-to-web/Chart.yaml
  charts/stable/rtsp-to-web/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/S

#1438 [blocky]: Upgrade appVersion and use it from chart.
  charts/stable/blocky/Chart.yaml
  charts/stable/blocky/values.yaml
Labels: precommit:ok, install:ok, lint:ok, changelog:ok, size/XS
